version: 2.1
jobs: 
  build: 
    working_directory: ~/tech-react/tech-react-component
    docker:
      - image: circleci/node:12.11.1
    steps:
      - checkout:
          path: ~/tech-react
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run: 
          name: install-npm
          command: npm install 
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ~/tech-react/tech-react-component/node_modules
      - run: 
          name: build
          command: npm run build 
      - run:
          name: build-story-book
          command: npm run build-storybook  
      - run:
          name: remove-docker
          command: rm -fr ../docs
      - run:
          name: move-storybook-static-docs
          command: mv storybook-static ../docs
      - run:
          name: git-config-email
          command: git config user.email "circleci@techoffice.com"
      - run:
          name: git-config-name
          command: git config user.name "circleci"
      - run: 
          name: add-docs
          command: git add ../docs
      - run:
          name: commit-docs
          command: git commit -m "[ci skip] build github page"
      - run:
          name: push-docs
          command: git push
